post http://localhost:3001/api/blogs 
Content-Type: application/json

{
  "title": "My Tuesday Morning",
  "author": "Mark",
  "url": "www.marloboticano.com",
  "likes": 8,
  "userId": "5d5b3163ebbec607a880c79e"
}